print("100+5")
print("Hola 'Murphy'")
print("Hola" + " "+ 'Murphy')
print("Me llamo \"Murphy\"")
print("Esta es una linea \ny esta es otra linea")
print("\t Esta es la tercera linea")
print('This isn\'t a number')
print("Este signo \\ es una barra invertida")
